# Generated by Django 3.1.3 on 2020-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201216_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='firstname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
